### ISSUE TITLE
Fatal error: Uncaught ValueError: 

### ISSUE THREAD

**Issue by pendalazo** [jenyraval/Phishing-Simulation#5]
Hello

I am stuck on the generate domain variation step; it is not generating anything and after entering the info manually, I am not able to preview the phished page and I am getting the error bellow.

" Warning: preg_match(): Compilation failed: invalid range in character class at offset 119 in C:\xampp\htdocs\AdminPanel\includes\url_to_absolute.php on line 342

Fatal error: Uncaught ValueError: Path cannot be empty in C:\xampp\htdocs\AdminPanel\includes\htmlSaveComplete.php:487 Stack trace: #0 C:\xampp\htdocs\AdminPanel\includes\htmlSaveComplete.php(487): file_get_contents('') https://github.com/jenyraval/Phishing-Simulation/issues/1 C:\xampp\htdocs\AdminPanel\includes\htmlSaveComplete.php(543): htmlSaveComplete->getContents(false) https://github.com/jenyraval/Phishing-Simulation/issues/2 [internal function]: htmlSaveComplete->createDataUri(Array) https://github.com/jenyraval/Phishing-Simulation/issues/3 C:\xampp\htdocs\AdminPanel\includes\htmlSaveComplete.php(239): preg_replace_callback('#(url\(['\"]?)(...', Array, '...') https://github.com/jenyraval/Phishing-Simulation/issues/4 C:\xampp\htdocs\AdminPanel\includes\htmlSaveComplete.php(139): htmlSaveComplete->toDataUri('...') #5 C:\xampp\htdocs\AdminPanel\saveCompletePage.php(21): htmlSaveComplete->getCompletePage(false, false, false) #6 {main} thrown in C:\xampp\htdocs\AdminPanel\includes\htmlSaveComplete.php on line 487"

regards
Penda

**Comment by AwaniCaleb** [comment]
Has this been resolved yet?

**Comment by pendalazo** [comment]
> Has this been resolved yet?

This is not yet resolved, but it's Okay because I have already submitted the project I was working on

**Comment by AwaniCaleb** [comment]
> > Has this been resolved yet?
> 
> This is not yet resolved, but it's Okay because I have already submitted the project I was working on

Was your project related to Phishing Simulation?

**Comment by pendalazo** [comment]
> > > Has this been resolved yet?
> > 
> > 
> > This is not yet resolved, but it's Okay because I have already submitted the project I was working on
> 
> Was your project related to Phishing Simulation?

Yes my project was about phishing simulation

**Comment by AwaniCaleb** [comment]
> > > > Has this been resolved yet?
> > > 
> > > 
> > > This is not yet resolved, but it's Okay because I have already submitted the project I was working on
> > 
> > Was your project related to Phishing Simulation?
> 
> Yes my project was about phishing simulation

Alright, can I have that please 🥲
